const fetch = require("node-fetch"); // If using Node.js, install with: npm install node-fetch

const API_URL = "http://localhost:3000/api/v1/brand/newmodel"; // Replace with your actual API endpoint

const smartphoneModels = {
    "Samsung": [
        "Galaxy A02",
        "Galaxy A02s",
        "Galaxy A03",
        "Galaxy A03 Core",
        "Galaxy Note 10 Plus",
        "Galaxy Note 10",
        "Galaxy Note 10 Lite",
        "Galaxy Note 9",
        "Galaxy Note 8",
        "Galaxy Note 7",
        "Galaxy Note 5",
        "Galaxy A01 Core",
        "Galaxy A03s",
        "Galaxy A04s",
        "Galaxy A10",
        "Galaxy A10s",
        "Galaxy A12",
        "Galaxy A13",
        "Galaxy A13 (5G)",
        "Galaxy A14 (5G)",
        "Galaxy A15 (5G)",
        "Galaxy A2 Core",
        "Galaxy A20",
        "Galaxy A20E",
        "Galaxy A20s",
        "Galaxy A21",
        "Galaxy A21s",
        "Galaxy A22",
        "Galaxy A22 (5G)",
        "Galaxy A23",
        "Galaxy A3 (2016)",
        "Galaxy A30",
        "Galaxy A30s",
        "Galaxy A31",
        "Galaxy A32",
        "Galaxy A32 (5G)",
        "Galaxy A33",
        "Galaxy A34 (5G)",
        "Galaxy A35",
        "Galaxy A42 (5G)",
        "Galaxy A5",
        "Galaxy A5 (2016)",
        "Galaxy A5 2017",
        "Galaxy A50",
        "Galaxy A50s",
        "Galaxy A51",
        "Galaxy A52",
        "Galaxy A52s 5G",
        "Galaxy A53 (5G)",
        "Galaxy A54",
        "Galaxy A55",
        "Galaxy A6",
        "Galaxy A6 Plus",
        "Galaxy A60",
        "Galaxy A7",
        "Galaxy A7 (2018)",
        "Galaxy A70",
        "Galaxy A71",
        "Galaxy A72",
        "Galaxy A73",
        "Galaxy A8 (2018)",
        "Galaxy A8 Plus",
        "Galaxy A8s",
        "Galaxy A80",
        "Galaxy A9 (2018)",
        "Galaxy F12",
        "Galaxy F13",
        "Galaxy F14",
        "Galaxy F22",
        "Galaxy F23 (5G)",
        "Galaxy F34",
        "Galaxy F41",
        "Galaxy F42 (5G)",
        "Galaxy F54",
        "Galaxy F62",
        "Galaxy M01",
        "Galaxy M01 Core",
        "Galaxy M01s",
        "Galaxy M02",
        "Galaxy M02s",
        "Galaxy M10",
        "Galaxy M10s",
        "Galaxy M11",
        "Galaxy M12",
        "Galaxy M13",
        "Galaxy M14",
        "Galaxy M20",
        "Galaxy M21",
        "Galaxy M21 (2021) Edition",
        "Galaxy M22",
        "Galaxy M30",
        "Galaxy M30s",
        "Galaxy M31",
        "Galaxy M31s",
        "Galaxy M32",
        "Galaxy M32 (5G)",
        "Galaxy M33 (5G)",
        "Galaxy M34",
        "Galaxy M35",
        "Galaxy M40",
        "Galaxy M42",
        "Galaxy M51",
        "Galaxy M52",
        "Galaxy M53",
        "Galaxy M55",
        "Galaxy M62",
        "Galaxy Z Fold",
        "Galaxy Z Flip",
        "Galaxy Z Flip 3 5G",
        "Galaxy Z Flip ",
        "Galaxy Z Fold 2",
        "Galaxy Z Fold 3 (5G)",
        "Galaxy Z Fold 4 (5G)",
        "Galaxy Z Flip 5",
        "Galaxy Z Fold 5",
        "Galaxy J4 Plus",
        "Galaxy J5 (2017)",
        "Galaxy J5 Pro",
        "Galaxy J6 Plus",
        "Galaxy J6",
        "Galaxy J7",
        "Galaxy J7 (2017)",
        "Galaxy J7 Max",
        "Galaxy J7 Pro",
        "J7 Prime",
        "Galaxy J8 2018",
        "Galaxy On Nxt",
        "Galaxy On5 (2016)"
    ],
    "OnePlus": [
        "OnePlus12",
        "OnePlus12R",
        "OnePlus 11",
        "OnePlus 11R",
        "OnePlus 3T",
        "OnePlus 6",
        "OnePlus 7T",
        "OnePlus 7T Pro",
        "OnePlus 7",
        "OnePlus 7 Pro",
        "OnePlus Nord N200 (5G)",
        "OnePlus Nord N20 5G",
        "OnePlus Nord N100",
        "OnePlus Nord 5G",
        "OnePlus Nord 2T",
        "OnePlus Nord 2 5G",
        "OnePlus Nord 3 5G",
        "OnePlus Nord 4 5G",
        "OnePlus Nord CE",
        "OnePlus Nord CE 2 Lite",
        "OnePlus Nord CE 2",
        "OnePlus Nord CE 3 Lite",
        "OnePlus Nord CE 3",
        "OnePlus Nord CE 4 Lite",
        "OnePlus Nord CE 4",
        "OnePlus 8T",
        "OnePlus 8",
        "OnePlus 8 Pro",
        "OnePlus 9RT",
        "OnePlus 9R",
        "OnePlus 9",
        "OnePlus 9 Pro",
        "OnePlus 10T",
        "OnePlus 10R",
        "OnePlus 10Pro"
    ],
    "Oppo": [
        "Oppo F25 Pro",
        "Oppo Reno",
        "Reno 12 Pro",
        "Reno 11 Pro",
        "Reno 11",
        "Reno 10x Zoom",
        "Reno 10 5G",
        "Reno 10 Pro Plus",
        "Reno 8 (4G)",
        "Reno 8 5G",
        "Reno 8 Pro 5G",
        "Reno 8T 5G",
        "Reno 7 5G",
        "Reno 7 Pro 5G",
        "Reno 7 Z 5G",
        "Reno 6 4G",
        "Reno 6 5G",
        "Reno 6 Pro 5G",
        "Reno 5 4G",
        "Reno 5 5G",
        "Reno 5 Lite",
        "Reno 5 Pro",
        "Reno 5 Z 5G",
        "Reno 4",
        "Reno4 Pro",
        "F21 Pro 5G",
        "F21 Pro 4G",
        "F21s",
        "F21s Pro",
        "Find X",
        "Reno 4 Pro",
        "Reno 3",
        "Reno3 Pro",
        "Reno 2 F",
        "Reno2 Z",
        "F9 Pro",
        "F7",
        "RX17",
        "Oppo A5 (2020)",
        "Oppo K3",
        "Oppo A3 Pro",
        "Oppo A1",
        "Oppo A11k",
        "Oppo A12",
        "Oppo A15",
        "Oppo A15s",
        "Oppo A16",
        "Oppo A16e",
        "Oppo A16K",
        "Oppo F27 Pro Plus 5G"
    ],
    "Poco": [
        "Poco X6 Pro",
        "Poco X5 Pro 5G",
        "Poco X4 Pro 5G",
        "Poco X3 Pro",
        "Poco X3",
        "Poco X2",
        "Poco F6",
        "Poco F5",
        "Poco F4 (5G)",
        "POCO F3 GT (5G)",
        "Poco F1",
        "Poco M6 (5G)",
        "POCO M5 (5G)",
        "Poco M4 (5G)",
        "Poco M4 Pro (5G)",
        "POCO M3 Pro 5G",
        "POCO M3",
        "Poco M2",
        "Poco M2 Pro",
        "Poco C31",
        "POCO C3"
    ],
    "Vivo": [
        "X200",
        "X100",
        "X100 Pro",
        "X90 Pro",
        "X90",
        "X90 Plus",
        "X80 Pro",
        "X80",
        "X60",
        "X60 PRO",
        "X60 Pro Plus",
        "X50 Pro",
        "X50",
        "X27",
        "X21",
        "Xplay 5",
        "V40",
        "V30",
        "V30 Pro",
        "V29 Pro",
        "V29",
        "V29e",
        "V27 Pro",
        "V27",
        "V25 Pro",
        "V25 (5G)",
        "V25 Pro (5G)",
        "V23 (5G)",
        "V23 Pro",
        "V23 Pro (5G)",
        "V23e (5G)",
        "V21 (5G)",
        "V21",
        "V21e",
        "V21e (5G)",
        "V20",
        "V20 Pro",
        "V20 SE(V2022)",
        "V2026 ",
        "(Y12s)",
        "V19",
        "V17",
        "V17 Pro",
        "V15",
        "V15 Pro",
        "V11",
        "V11 Pro",
        "V9",
        "V9 Pro",
        "V9 Youth",
        "V7",
        "V7 Plus",
        "V5",
        "V5 Plus",
        "V5s",
        "V3",
        "NEX A",
        "NEX S",
        "S1",
        "S1 pro",
        "T3 (5G)",
        "T3X (5G)",
        "T2 Pro",
        "T2 5G",
        "T2X 5G",
        "T1 Pro (5G)",
        "T1",
        "T1 (5G)",
        "T1X",
        "U10",
        "U20",
        "V30",
        "Y01",
        "Y11",
        "Y12",
        "Y12s",
        "Y12G",
        "Y15 (2019)",
        "X100 PRO",
        "Y15c",
        "Y15s",
        "Y16",
        "Y17",
        "Y19",
        "Y1s",
        "Y1s (2020)",
        "Y20",
        "Y20G",
        "Y20i",
        "Y21 (2021)",
        "Y21e",
        "Y21G",
        "Y21T",
        "Y22 (2022)"
    ],
    "Xiaomi": [
        "Xiaomi 14",
        "Xiaomi 13 Pro",
        "Xiaomi 14 Civi",
        "Redmi Note 13 Pro",
        "Redmi Note 13",
        "Redmi Note 12 Pro 5G",
        "Redmi Note 12",
        "Redmi Note 11 Pro Plus 5G",
        "Redmi Note 11 Pro",
        "Redmi Note 11S",
        "Redmi Note 11T (5G)",
        "Redmi Note 11",
        "Xiaomi 12 Pro",
        "Xiaomi 12X",
        "Xiaomi Mi 11T Pro",
        "Xiaomi Mi 11 Ultra",
        "Xiaomi 11 Lite NE 5G",
        "Xiaomi Mi 11i",
        "Xiaomi Mi 11X Pro",
        "Xiaomi Mi 11X",
        "Xiaomi Mi 11 Lite",
        "Xiaomi Mi 10T",
        "Xiaomi Mi 10",
        "Mi 10i",
        "Mi Note 10 Lite",
        "Mi Note 10",
        "Redmi Note 13 pro Plus",
        "Redmi 13 Pro",
        "Redmi 13C",
        "Redmi 12 5G",
        "Redmi 11 Prime (5G)",
        "Redmi 10 Prime",
        "Redmi 10A",
        "Redmi 10",
        "Redmi Note 10 Pro Max",
        "Redmi Note 10 Pro",
        "Redmi Note 10S",
        "Redmi Note 10T (5G)",
        "Redmi Note 10",
        "Redmi Note 10 Lite",
        "Xiaomi Mi Mix 2S",
        "Xiaomi Mi Mix 2"
    ],
    "Realme": [
        "Realme Gt Master Edition",
        "Realme GT 2 (5G)",
        "Realme GT 2 Pro",
        "Realme GT 5G",
        "Realme GT Neo 2 (5G)",
        "Realme GT Neo 3 (5G)",
        "Realme GT Neo 3T (5G)",
        "Realme GT 6T",
        "Realme GT 6",
        "Realme X7 Pro",
        "Realme X7 Max",
        "Realme X7 Max 5G",
        "Realme X7",
        "Realme X50 Pro 5G",
        "Realme X3",
        "Realme X3 Superzoom",
        "Realme X2",
        "Realme X2 Pro",
        "Realme X",
        "Realme XT",
        "Realme 13 Pro 5G",
        "Realme 12",
        "Realme 12 Pro",
        "Realme 12 Plus",
        "Realme 12 Pro Plus",
        "Realme 11 pro 5g",
        "Realme 11x (5G)",
        "Realme 10 Pro Plus",
        "Realme 10 Pro (5G)",
        "Realme 9",
        "Realme 9 SE",
        "Realme 9 Pro (5G)",
        "Realme 9 Pro (5G)",
        "Realme 9 Pro Plus (5G)",
        "Realme 9i",
        "Realme 9i (5G)",
        "Realme 8",
        "Realme 8 (5G)",
        "Realme 8 Pro",
        "Realme 8i",
        "Realme 8s (5G)",
        "Realme 7",
        "Realme 7 Pro",
        "Realme 7i",
        "Realme 6",
        "Realme 6 Pro",
        "Realme 6i",
        "Realme 5",
        "Realme 5 Pro",
        "Realme 5i",
        "Realme 5s",
        "Realme 3",
        "Realme 3 Pro",
        "Realme 3i",
        "Realme 2",
        "Realme 2 Pro",
        "Realme 1"
    ],
    "iQOO": [
        "iQOO 12 5G",
        "iQOO 12",
        "iQOO 11",
        "iQOO 9T",
        "iQOO 9 Pro",
        "iQOO 9 SE",
        "iQOO 9",
        "iQOO 7 5G",
        "iQOO 3 5G",
        "iQOO Z9 5G",
        "iQOO Z7 Pro",
        "iQOO Z7s",
        "iQOO Z6 Pro (5G)",
        "iQOO Z6 (5G)",
        "iQOO Z6 Lite (5G)",
        "iQOO Z5 (5G)",
        "iQOO Z3 (5G)",
        "iQOO Neo 9 Pro",
        "iQOO Neo 7",
        "iQOO Neo 6",
        "iQOO Neo 3"
    ],
    "Google": [
        "Pixel 9 XL",
        "Pixel 7a",
        "Pixel 6 Pro 5G",
        "Pixel 6a",
        "Pixel 6",
        "Pixel 5",
        "Pixel 4",
        "Pixel 4 XL",
        "Pixel 4a",
        "Pixel 3",
        "Pixel 3a",
        "Pixel 3a XL",
        "Pixel 3 XL",
        "Pixel 2",
        "Pixel 2 XL",
        "Pixel 5a",
        "Pixel XL"
    ],
    "Apple": [
        "iPhone 11 Pro Max",
        "iPhone 11 Pro",
        "iPhone 11",
        "iPhone SE 2022",
        "iPhone SE 2020",
        "iPhone XS Max",
        "iPhone XS",
        "iPhone XR",
        "iPhone X",
        "iPhone 8 Plus",
        "iPhone 8",
        "iPhone 7 Plus",
        "iPhone 7",
        "iPhone 6 Plus",
        "iPhone 6",
        "iPhone 6S Plus",
        "iPhone 6S"
    ],
    "Infinix": [
        "Infinix Note 40 Pro 5G",
        "Infinix Note 40 5G",
        "Infinix Hot 50 5G",
        "Infinix Note 40X",
        "Infinix Note 40i",
        "Infinix Smart 8",
        "Infinix GT 20 Pro 5G",
        "Infinix GT 10 Pro 5G",
        "Infinix GT 40 Pro 5G"
    ]
}

async function addModels() {
    for (const [brand, models] of Object.entries(smartphoneModels)) {
        for (const model of models) {
            const payload = { 
                categoryName: "smartphone", 
                brandName: brand, 
                modelName: model 
            };

            try {
                const response = await fetch(API_URL, {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify(payload)
                });

                const data = await response.json();
                console.log(`Added: ${brand} - ${model}`, data);
            } catch (error) {
                console.error(`Error adding ${brand} - ${model}:`, error);
            }
        }
    }
}

addModels();
